development:
  adapter: postgresql
  encoding: unicode
  database: rails-angularjs-example_development
  host: localhost
  pool: 5
  username: development
  password: development

test:
  adapter: postgresql
  encoding: unicode
  database: rails-angularjs-example_test
  host: localhost
  pool: 5
  username: development
  password: development
